coucou:
  build: .
  links:
    - sling
  command: build bundleInstall
  volumes_from:
    - coucou-gradle-cache
#coucou-api:
#  build: coucou-api
#  volumes_from:
#    - coucou-api-gradle-cache
whistlepost:
  image: micronode/whistlepost
  links:
    - sling
  command: build bundleInstall
  volumes_from:
    - whistlepost-gradle-cache
sling:
  image: apachesling/sling
  mem_limit: 512m
#  links:
#    - "coucou-api:api"
  volumes:
    - "./sling.properties:/opt/sling/sling.properties"
  volumes_from:
    - sling-data
sling-data:
  image: tianon/true
  volumes:
    - /opt/sling/sling
haproxy:
  image: tutum/haproxy
  links:
    - sling
  ports:
    - "80:80"
    - "1936:1936"
  mem_limit: 128m
coucou-gradle-cache:
  image: cogniteev/echo:latest
  volumes:
    - /root/.gradle
coucou-api-gradle-cache:
  image: cogniteev/echo:latest
  volumes:
    - /root/.gradle
whistlepost-gradle-cache:
  image: cogniteev/echo:latest
  volumes:
    - /root/.gradle
