version: "3"
services:
  whistlepost:
    image: "micronode/whistlepost:1.1.5-develop-SNAPSHOT"
    ports:
      - "8081:8080"
    volumes:
      - ./src/app:/wp/apps/coucou:ro
      - ./src/assets:/wp/assets/coucou:ro
      - ./src/content:/wp/content/coucou:ro

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
